services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: full-stack-ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/full-stack-ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: com.mysql.cj.jdbc.Driver
      SPRING_APPLICATION_NAME: ecommerce
      SPRING_DATA_REST_BASE_PATH: /api/v1
      STRIPE_KEY_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce-net

volumes:
  mysql_data:

networks:
  ecommerce-net:
    driver: bridge